import React from "react";
import Head from "next/head";
import styles from "../styles/About.module.scss";
import Title from "../components/Title/Title";
import Subtitle from "../components/Subtitle/Subtitle";
import Button from "../components/Button/Button";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faDownload } from "@fortawesome/free-solid-svg-icons";

import Card from "../components/Card/Card";
const aboutPage = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="pageContainer">
        <div className={styles.title}>
          <Title text1="About" text2="Me"></Title>
        </div>

        <div className={styles.overview}>
          <div className={styles.info}>
            <Subtitle text="Information" />
            <p>
              1 year learning story with Javascript and Typescript. Start with
              taking and completing Purwadhika Full Stack Web Development
              program.
            </p>
            <p>
              Implement what i've learned to couple of projects with different
              frameworks such as React JS, Next JS, and Vite JS. each project
              have different level of complexity.
            </p>
            <p>
              because of the technology is always evolving and moving forward. i
              think we, and especially me as a web developer, should be adapt
              and improvise with new tech innovation in the future. and that is
              what I aspire to be
            </p>
            <Button text="Download CV">
              <FontAwesomeIcon icon={faDownload} />
            </Button>
          </div>
          <div className={styles.staticCard}>
            <Card number={1} title="Year Experience" />
            <Card number={4} title="Project Completed" />
            <Card number={3} title="Framework" />
            <Card number={2} title="Language" />
          </div>
        </div>

        {/* html, css, sass, js, ts, react, nextjs, nodejs  */}
        <div className={styles.learned}>
          <Subtitle text="What I Have Learned" />

          <div className={styles.learnedItems}>
            <div className={styles.learnedItem}>
              <img src="/icons/html-5.svg" alt="html-icon" />
              <p className={styles.itemName}>Html 5</p>
            </div>
            <div className={styles.learnedItem}>
              <img src="/icons/css3.svg" alt="css-icon" />
              <p className={styles.itemName}>Css 3</p>
            </div>
            <div className={styles.learnedItem}>
              <img src="/icons/sass.svg" alt="sass-icon" />
              <p className={styles.itemName}>Sass</p>
            </div>
            <div className={styles.learnedItem}>
              <img src="/icons/tailwind.svg" alt="tailwind-icon" />
              <p className={styles.itemName}>Tailwind</p>
            </div>
            <div className={styles.learnedItem}>
              <img src="/icons/javascript.svg" alt="js-icon" />
              <p className={styles.itemName}>Javascript</p>
            </div>
            <div className={styles.learnedItem}>
              <img src="/icons/typescript.svg" alt="ts-icon" />
              <p className={styles.itemName}>Typescript</p>
            </div>
            <div className={styles.learnedItem}>
              <img src="/icons/react.svg" alt="react-icon" />
              <p className={styles.itemName}>React</p>
            </div>
            <div className={styles.learnedItem}>
              <img src="/icons/nextjs-round.svg" alt="nextJs-icon" />
              <p className={styles.itemName}>Next</p>
            </div>
            <div className={styles.learnedItem}>
              <img src="/icons/Vitejs.svg" alt="vitejs-icon" />
              <p className={styles.itemName}>Vite JS</p>
            </div>
            <div className={styles.learnedItem}>
              <img src="/icons/node-js.svg" alt="nodeJs-icon" />
              <p className={styles.itemName}>Node JS</p>
            </div>
            <div className={styles.learnedItem}>
              <img src="/icons/mongodb.svg" alt="mongodb-icon" />
              <p className={styles.itemName}>MongoDb</p>
            </div>
            <div className={styles.learnedItem}>
              <img src="/icons/mysql.svg" alt="mysql-icon" />
              <p className={styles.itemName}>MySql</p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default aboutPage;
