import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faDownload } from "@fortawesome/free-solid-svg-icons";
import Button from "../components/Button/Button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.headerContainer}>
        <div className={styles.leftHeader}>
          <div className={styles.shapedColor}></div>
          <div className={styles.heroImg}>
            <img src="./img/hero.png" alt="Hero Image" />
          </div>
        </div>
        <div className={styles.rightHeader}>
          <h1 className={styles.name}>
            Hi i'm <span>Ayyas</span> <br /> A Web Developer
          </h1>
          <div className={styles.paragraph}>
            <p>
              A fresh graduated that passionate about website development. learn
              from basic until now experienced using React JS, Vite JS, Next JS,
              Tailwind, Node JS, Mysql and MongoDb.
            </p>
            <p>
              Having couple of projects, from simple to complex, from doing
              alone to collaborate, and from just frontend to fullstack.
            </p>
            <p>
              I aspire to be a web developer who can keep up with new tech
              innovation.
            </p>
          </div>
          <Button text="Download CV">
            <FontAwesomeIcon icon={faDownload} />
          </Button>
        </div>
      </header>
    </>
  );
}
