import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faDownload } from '@fortawesome/free-solid-svg-icons';
import Button from '../components/Button/Button';
const link = process.env.CV_LINK;

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.headerContainer}>
        <div className={styles.leftHeader}>
          <div className={styles.shapedColor}></div>
          <div className={styles.heroImg}>
            <img src="./img/hero.png" alt="Hero Image" />
          </div>
        </div>
        <div className={styles.rightHeader}>
          <h1 className={styles.name}>
            Hi i'm <span>Ayyas</span> <br /> A Web Developer
          </h1>
          <div className={styles.paragraph}>
            <p>
              An IT enthusiast focused on Front-End development with an educational background in
              Full-Stack. Has 3 years of experience in various projects with satisfactory results.
            </p>
            <p>
              Oriented in quality, efficiency, and optimization in coding. Committed to delivering
              innovative and impactful solutions in every project
            </p>
          </div>
          <Button text="Download CV">
            <FontAwesomeIcon icon={faDownload} />
          </Button>
        </div>
      </header>
    </>
  );
}
