import React from "react";
import Head from "next/head";

const projectPage = () => {
  return (
    <>
      <Head>
        <title>Project Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Project Page</h2>
    </>
  );
};

export default projectPage;
